train:
  epoch: 500
  batch_size: 32
  resume: null # "/workspace/My-reserch-project/WavetableVAE/28tspm6i/checkpoints/epoch=1431-step=141768.ckpt"
  auto_lr_find: True
  auto_scale_batch_size: True

model:
  duplicate_num: 30
  latent_dim: 512
  enc_cond_layer: [True, True, True, True]
  dec_cond_layer: [True, True, True, True]

data:
  sample_points: 600
  sample_rate: 44100

save: "-ess-yeojohnson-dec1000"
seed: 42
experiment_name: "Wavetable-VAE"
savename: "Wavetable-VAE"