train:
  epoch: 1
  batch_size: 32
  resume: False
  auto_lr_find: True
  auto_scale_batch_size: True

model:
  sample_points: 600
  beta: 0.01

save: "-ess-yeojohnson-beta001-dec1111"
seed: 42
experiment_name: "Wavetable-VAE"
savename: "Wavetable-VAE"